language: go

dist:
  - trusty
  - xenial

sudo: false

go:
  - 1.11.x
  - master

install:
  - go get github.com/gorilla/websocket

script:
  - go test ./...
  - go vet main.go
  - go vet src/**/*.go
  - go build main.go
