version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS # create the test results directory

      - restore_cache: # restores saved cache if no changes are detected since last run
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      # Normally, this step would be in a custom primary image;
      # we've added it here for the sake of explanation.
      - run: ls -R
      - run: go get github.com/gorilla/websocket
      - run: go build github.com/IITH-SBJoshi/concurrency-3/main.go
      - run: go test -v github.com/IITH-SBJoshi/concurrency-3/src/client
      - run: go test -v github.com/IITH-SBJoshi/concurrency-3/src/coords
      - run: go test -v github.com/IITH-SBJoshi/concurrency-3/src/dijkstra
      - run: go test -v github.com/IITH-SBJoshi/concurrency-3/src/dtypes
      - run: go test -v github.com/IITH-SBJoshi/concurrency-3/src/handlers
      - run: go test -v github.com/IITH-SBJoshi/concurrency-3/src/health
